package Pantallas;

import Modelos.SQLClientes;
import Pantallas.Pedidos;
import com.mysql.cj.protocol.Resultset;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author karin
 */
public class Perfil extends javax.swing.JFrame {

    DefaultTableModel model;
    DefaultTableModel modeltar;
    int id_cl;
    String cont;
    String dir1;
    String dir2;
    String tar;
    String [] datos2;

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        initComponents();
        this.setSize(451, 600);
        pnlDirecciones.setVisible(false);
        pnlPass.setVisible(false);
        pnlTarjetas.setVisible(false);
    }

    public Perfil(String[] datos) {
        initComponents();
        this.setSize(481, 600);
        pnlDirecciones.setVisible(false);
        pnlPass.setVisible(false);
        pnlTarjetas.setVisible(false);
        lbNombre.setText(datos[2]);
        lbUsuario.setText(datos[1]);
        cont = datos[5];
        id_cl = Integer.parseInt(datos[0]);
        dir1 = datos[6];
        dir2 = datos[7];
        model = (DefaultTableModel) jTable2.getModel();
        modeltar = (DefaultTableModel) tbTarjetas.getModel();
        tar = datos[9];
        datos2 = datos;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlTarjetas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTarjetas = new javax.swing.JTable();
        btnAgregarTar = new javax.swing.JButton();
        txttar = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtcvv = new javax.swing.JTextField();
        pnlOp = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        cbxOpciones = new javax.swing.JComboBox();
        btnContinuar = new javax.swing.JButton();
        lbNombre = new javax.swing.JTextField();
        lbUsuario = new javax.swing.JTextField();
        pnlPass = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtPassActual = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPassNueva = new javax.swing.JPasswordField();
        txtPassConfirmar = new javax.swing.JPasswordField();
        btnGuardar = new javax.swing.JButton();
        pnlDirecciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnDirecciones = new javax.swing.JButton();
        txtdirnueva = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tbTarjetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tarjetas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbTarjetas);

        btnAgregarTar.setText("Agregar Tarjeta");
        btnAgregarTar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTarActionPerformed(evt);
            }
        });

        txttar.setText("tarjeta");

        txtfecha.setText("fecha de vencimiento");

        txtcvv.setText("CVV");

        javax.swing.GroupLayout pnlTarjetasLayout = new javax.swing.GroupLayout(pnlTarjetas);
        pnlTarjetas.setLayout(pnlTarjetasLayout);
        pnlTarjetasLayout.setHorizontalGroup(
            pnlTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetasLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnAgregarTar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTarjetasLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(pnlTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlTarjetasLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(pnlTarjetasLayout.createSequentialGroup()
                        .addComponent(txttar)
                        .addGap(18, 18, 18)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtcvv, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        pnlTarjetasLayout.setVerticalGroup(
            pnlTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTarjetasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnAgregarTar)
                .addContainerGap())
        );

        pnlOp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        cbxOpciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cambiar Contraseñas", "Mis pagos", "Administrar direcciones", "Pedidos" }));

        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        lbNombre.setText("nombre");
        lbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNombreActionPerformed(evt);
            }
        });

        lbUsuario.setText("usuario");

        javax.swing.GroupLayout pnlOpLayout = new javax.swing.GroupLayout(pnlOp);
        pnlOp.setLayout(pnlOpLayout);
        pnlOpLayout.setHorizontalGroup(
            pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpLayout.createSequentialGroup()
                .addGroup(pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOpLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(cbxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOpLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNombre)
                            .addGroup(pnlOpLayout.createSequentialGroup()
                                .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))))
                .addGap(43, 43, 43)
                .addGroup(pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar)
                    .addComponent(btnContinuar))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlOpLayout.setVerticalGroup(
            pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpLayout.createSequentialGroup()
                .addGroup(pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOpLayout.createSequentialGroup()
                        .addComponent(lbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlOpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnActualizar)))
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(pnlOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinuar))
                .addGap(23, 23, 23))
        );

        jLabel4.setText("Contraseña actual");

        jLabel5.setText("Nueva Contraseña");

        jLabel6.setText("Confirmar contraseña");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPassLayout = new javax.swing.GroupLayout(pnlPass);
        pnlPass.setLayout(pnlPassLayout);
        pnlPassLayout.setHorizontalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPassLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPassConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(pnlPassLayout.createSequentialGroup()
                        .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPassActual)
                            .addComponent(txtPassNueva))))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(26, 26, 26))
        );
        pnlPassLayout.setVerticalGroup(
            pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPassLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPassActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnGuardar)
                    .addComponent(txtPassNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(pnlPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPassConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Direcciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnDirecciones.setText("Agregar Dirección");
        btnDirecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDireccionesActionPerformed(evt);
            }
        });

        txtdirnueva.setText(" ");

        javax.swing.GroupLayout pnlDireccionesLayout = new javax.swing.GroupLayout(pnlDirecciones);
        pnlDirecciones.setLayout(pnlDireccionesLayout);
        pnlDireccionesLayout.setHorizontalGroup(
            pnlDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionesLayout.createSequentialGroup()
                .addGroup(pnlDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDireccionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(pnlDireccionesLayout.createSequentialGroup()
                        .addGroup(pnlDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDireccionesLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(btnDirecciones))
                            .addGroup(pnlDireccionesLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txtdirnueva, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDireccionesLayout.setVerticalGroup(
            pnlDireccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDireccionesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtdirnueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnDirecciones)
                .addGap(26, 26, 26))
        );

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(pnlDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlOp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(btnRegresar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(pnlOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(18, 18, 18)
                .addComponent(pnlPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTarjetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDirecciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        
        
        model.setRowCount(0);
        modeltar.setRowCount(0);
        if (cbxOpciones.getSelectedItem().equals("Cambiar Contraseñas")) {
            pnlDirecciones.setVisible(false);
            pnlPass.setVisible(true);
            pnlTarjetas.setVisible(false);
        } else if (cbxOpciones.getSelectedItem().equals("Mis pagos")) {
            pnlDirecciones.setVisible(false);
            pnlPass.setVisible(false);
            pnlTarjetas.setVisible(true);
   
        } else if (cbxOpciones.getSelectedItem().equals("Administrar direcciones")) {
            pnlDirecciones.setVisible(true);
            pnlPass.setVisible(false);
            pnlTarjetas.setVisible(false);
        } else if (cbxOpciones.getSelectedItem().equals("Pedidos")) {
            pnlDirecciones.setVisible(false);
            pnlPass.setVisible(false);
            pnlTarjetas.setVisible(false);
            Pedidos objPedidos = new Pedidos(datos2);
            objPedidos.setVisible(true);
            this.setVisible(false);
        }

        if (!dir1.equals("")) {
            model.addRow(new Object[]{dir1});

        }
        if (!dir2.equals("")) {
            model.addRow(new Object[]{dir2});
        }
        try {
            if (!tar.equals("")) {
            modeltar.addRow(new Object[]{tar});
        } 
        } catch (Exception e) {
            System.out.println("error");
        }
        
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Principal objPrincipal = new Principal(datos2);
        objPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtPassNueva.getText().equals(txtPassConfirmar.getText())) {
            SQLClientes sqlc = new SQLClientes();
            String c = sqlc.comparar(txtPassActual.getText());
            String s = sqlc.comparar(txtPassNueva.getText());

            if (c.equals(cont)) {
                sqlc.ModificarCon(s, id_cl);
                JOptionPane.showMessageDialog(null, "Actualizacion correcta");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void lbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNombreActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        SQLClientes act = new SQLClientes();
        act.ModificarNom(id_cl, lbNombre.getText(), lbUsuario.getText());
        JOptionPane.showMessageDialog(null, "Actualizacion lista");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnDireccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDireccionesActionPerformed
        if (jTable2.getRowCount() == 2) {
            JOptionPane.showMessageDialog(null, "No puede agregar mas direcicones");
        } else if (dir1.equals("")) {
            SQLClientes dir = new SQLClientes();
            dir.direcciones(id_cl, txtdirnueva.getText());
            JOptionPane.showMessageDialog(null, "Direcciones agregada");
            dir1 = txtdirnueva.getText();
            txtdirnueva.setText("");
            model.addRow(new Object[]{dir1});
        } else {
            SQLClientes dire2 = new SQLClientes();
            dire2.direcciones2(id_cl, txtdirnueva.getText());
            JOptionPane.showMessageDialog(null, "Direcciones agregada");
            dir2 = txtdirnueva.getText();
            txtdirnueva.setText("");
            model.addRow(new Object[]{dir2});
        }


    }//GEN-LAST:event_btnDireccionesActionPerformed

    private void btnAgregarTarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTarActionPerformed
        if (tbTarjetas.getRowCount() == 1) {
            JOptionPane.showMessageDialog(null, "ya no puede agregar otra tarjeta");
        } else {
            SQLClientes targ = new SQLClientes();
            targ.Tar(id_cl, txttar.getText(), Integer.parseInt(txtcvv.getText()), txtfecha.getText());
            tar = txttar.getText();
            txttar.setText("");
            txtfecha.setText("");
            txtcvv.setText("");
            modeltar.addRow(new Object[]{tar});
        }
    }//GEN-LAST:event_btnAgregarTarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregarTar;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnDirecciones;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox cbxOpciones;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField lbNombre;
    private javax.swing.JTextField lbUsuario;
    private javax.swing.JPanel pnlDirecciones;
    private javax.swing.JPanel pnlOp;
    private javax.swing.JPanel pnlPass;
    private javax.swing.JPanel pnlTarjetas;
    private javax.swing.JTable tbTarjetas;
    private javax.swing.JPasswordField txtPassActual;
    private javax.swing.JPasswordField txtPassConfirmar;
    private javax.swing.JPasswordField txtPassNueva;
    private javax.swing.JTextField txtcvv;
    private javax.swing.JTextField txtdirnueva;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txttar;
    // End of variables declaration//GEN-END:variables
}
