package Pantallas;

import Pantallas.Perfil;
import Modelos.*;
import com.mysql.cj.protocol.Resultset;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author karin
 */
public class Principal extends javax.swing.JFrame {
    SQLClientes sqlcl = new SQLClientes();
    Clientes mod;
    Juegos objJuego;
    String [] d;

    public Principal() {
        initComponents();
    }

    public Principal(Clientes mod) {
        initComponents();
        this.mod = mod;
        lbNom_Usuario.setText(mod.getNom_Usuario());

    }

    public Principal(String[] datos) {
        initComponents();
        lbNom_Usuario.setText(datos[1]);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        lbNom_Usuario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbJuegos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btncomprar = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnJuegos = new javax.swing.JMenu();
        mnConsolas = new javax.swing.JMenu();
        cnPlay = new javax.swing.JMenuItem();
        cnNintendo = new javax.swing.JMenuItem();
        cnXbox = new javax.swing.JMenuItem();
        mnEstrenos = new javax.swing.JMenuItem();
        mnGenero = new javax.swing.JMenu();
        gnArcade = new javax.swing.JMenuItem();
        gnAventura = new javax.swing.JMenuItem();
        gnCarreras = new javax.swing.JMenuItem();
        gnDeportivo = new javax.swing.JMenuItem();
        gnDisparos = new javax.swing.JMenuItem();
        gnEstrategia = new javax.swing.JMenuItem();
        gnLucha = new javax.swing.JMenuItem();
        gnMusicales = new javax.swing.JMenuItem();
        gnRPG = new javax.swing.JMenuItem();
        gnSimulacion = new javax.swing.JMenuItem();
        mnMasVendidos = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        mvNintendo = new javax.swing.JMenuItem();
        mvXbox = new javax.swing.JMenuItem();
        mnPreventas = new javax.swing.JMenuItem();
        mnTodos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbNom_Usuario.setText("Nom_Usr");
        lbNom_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNom_UsuarioMouseClicked(evt);
            }
        });

        tbJuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_juego", "Nombre", "Precio", "Consola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbJuegos);

        jLabel1.setText("Nombre de juego");

        btncomprar.setText("Comprar");
        btncomprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprarActionPerformed(evt);
            }
        });

        mnJuegos.setText("Juegos");

        mnConsolas.setText("Consolas");

        cnPlay.setText("PlayStation");
        mnConsolas.add(cnPlay);

        cnNintendo.setText("Nintendo");
        mnConsolas.add(cnNintendo);

        cnXbox.setText("XBOX");
        cnXbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnXboxActionPerformed(evt);
            }
        });
        mnConsolas.add(cnXbox);

        mnJuegos.add(mnConsolas);

        mnEstrenos.setText("Estrenos");
        mnJuegos.add(mnEstrenos);

        mnGenero.setText("Genero");

        gnArcade.setText("Arcade");
        mnGenero.add(gnArcade);

        gnAventura.setText("Aventura");
        mnGenero.add(gnAventura);

        gnCarreras.setText("Carreras");
        mnGenero.add(gnCarreras);

        gnDeportivo.setText("Deportivo");
        mnGenero.add(gnDeportivo);

        gnDisparos.setText("Disparos");
        gnDisparos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnDisparosActionPerformed(evt);
            }
        });
        mnGenero.add(gnDisparos);

        gnEstrategia.setText("Estrategía");
        mnGenero.add(gnEstrategia);

        gnLucha.setText("Lucha");
        mnGenero.add(gnLucha);

        gnMusicales.setText("Musicales");
        gnMusicales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnMusicalesActionPerformed(evt);
            }
        });
        mnGenero.add(gnMusicales);

        gnRPG.setText("RPG");
        mnGenero.add(gnRPG);

        gnSimulacion.setText("Simulación");
        gnSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnSimulacionActionPerformed(evt);
            }
        });
        mnGenero.add(gnSimulacion);

        mnJuegos.add(mnGenero);

        mnMasVendidos.setText("Más Vendidos");

        jMenuItem26.setText("PlayStation");
        mnMasVendidos.add(jMenuItem26);

        mvNintendo.setText("Nintendo");
        mnMasVendidos.add(mvNintendo);

        mvXbox.setText("XBOX");
        mnMasVendidos.add(mvXbox);

        mnJuegos.add(mnMasVendidos);

        mnPreventas.setText("Preventas");
        mnJuegos.add(mnPreventas);

        mnTodos.setText("Todos");
        mnJuegos.add(mnTodos);

        jMenuBar1.add(mnJuegos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(55, 55, 55)
                .addComponent(lbNom_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btncomprar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(lbNom_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btncomprar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cnXboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnXboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnXboxActionPerformed

    private void gnDisparosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnDisparosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnDisparosActionPerformed

    private void lbNom_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNom_UsuarioMouseClicked
        // Arreglar que sea con doble clic

        if (evt.getClickCount() == 2) {
            
            String[] datos = sqlcl.extraer(lbNom_Usuario.getText());
            
            this.setVisible(false);
            Perfil objPerfil = new Perfil(datos);
            objPerfil.setVisible(true);

        }
    }//GEN-LAST:event_lbNom_UsuarioMouseClicked

    private void gnMusicalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnMusicalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnMusicalesActionPerformed

    private void gnSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnSimulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gnSimulacionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        SQLJuegos objSqlJuegos = new SQLJuegos();
        objJuego = objSqlJuegos.extraer(txtBusqueda.getText());
        DefaultTableModel model = (DefaultTableModel) tbJuegos.getModel();
        d = sqlcl.extraer(lbNom_Usuario.getText());
        model.setRowCount(0);
        model.addRow(objJuego.toArray());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btncomprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprarActionPerformed
        int fila = tbJuegos.getSelectedRow();
        Juego compra = new Juego(objJuego.getId_Videojuego() , d);
        compra.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btncomprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JToggleButton btncomprar;
    private javax.swing.JMenuItem cnNintendo;
    private javax.swing.JMenuItem cnPlay;
    private javax.swing.JMenuItem cnXbox;
    private javax.swing.JMenuItem gnArcade;
    private javax.swing.JMenuItem gnAventura;
    private javax.swing.JMenuItem gnCarreras;
    private javax.swing.JMenuItem gnDeportivo;
    private javax.swing.JMenuItem gnDisparos;
    private javax.swing.JMenuItem gnEstrategia;
    private javax.swing.JMenuItem gnLucha;
    private javax.swing.JMenuItem gnMusicales;
    private javax.swing.JMenuItem gnRPG;
    private javax.swing.JMenuItem gnSimulacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNom_Usuario;
    private javax.swing.JMenu mnConsolas;
    private javax.swing.JMenuItem mnEstrenos;
    private javax.swing.JMenu mnGenero;
    private javax.swing.JMenu mnJuegos;
    private javax.swing.JMenu mnMasVendidos;
    private javax.swing.JMenuItem mnPreventas;
    private javax.swing.JMenuItem mnTodos;
    private javax.swing.JMenuItem mvNintendo;
    private javax.swing.JMenuItem mvXbox;
    private javax.swing.JTable tbJuegos;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables
}
